### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by drice89** [drice89/slockify#2]
- [x] Users can sign up, sign in, log out
- [x] Users can use a demo login to try the site
- [ ] Users can't use certain features without logging in (like reaching the app) (auth/protected routes)
- [ ] Errors should clear when moving between pages
- [ ] logout button should be added to splash page (a dropdown)

**Comment by drice89** [comment]
@jenvomo The logout button is burried in the authform - as far as i can tell slack doesnt actually have one
You wont be able to tell the if the last one is working until i get the client up which should happen today.

**Comment by jenvomo** [comment]
Splash page and session form look awesome! 

The only feedback I have:
- [ ]  increase the text size of all the stuff in the navbar as it is a bit small and hard to read.  

GREAT job on all of this!
